### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by sole** [mozilla/node-firefox-find-simulators#2]
Probably to test lib/platform.js to make sure they return what is expected in each platform
Maybe we need to abstract more stuff out of index.js and into a library and export it from a module so it can be tested.

**Comment by lmorchard** [comment]
I could take a poke at this, as part of wrapping my head around the libs

**Comment by tofumatt** [comment]
Sounds good!

-tofumatt

On 23 January 2015 at 14:50:16, Les Orchard (notifications@github.com) wrote:

I could take a poke at this, as part of wrapping my head around the libs

**Comment by tofumatt** [comment]
Fixed in cb99462

**Comment by brittanystoroz** [comment]
This should be closed, yes? @tofumatt @lmorchard   o_O

**Comment by tofumatt** [comment]
Indeed, I must've hit the wrong button. Thanks.
