### ISSUE TITLE
The binary path for 1.x simulators is wrong

### ISSUE THREAD

**Issue by sole** [mozilla/node-firefox-find-simulators#5]
The returned path is wrong at least in Mac OS--they substantially differ between 1.x and 2.x simulators

I am also not sure if these simulators accept the same command line parameters as 2.x

**Comment by tofumatt** [comment]
Some of the early simulators I think we can't communicate with, right? So like, we're aiming for 1.2 and above, yes?

**Comment by sole** [comment]
I think so! Definitely 1.2+ according to the docs in firefox-client: https://github.com/harthur/firefox-client#firefox-os-12-simulator-and-devices

the issue is just that the binary path we "build" is different for 1.x, it's a matter of determining which version is it and then building a different one.

**Comment by brittanystoroz** [comment]
Sorry @tofumatt did not see that you had assigned this to yourself. Was playing around with this and it looks like it's actually only simulators <=1.3 (1.4 follows the same path as 2.x versions).  I started a branch here:  https://github.com/brittanystoroz/node-firefox-find-simulators/tree/binary-paths

The path for 1.3 I found to be: `/resources/fxos_1_3_simulator/data/mac64/B2G.app/Contents/MacOS/b2g-bin`

But when I try to start up a 1.3, even with the right binary path, it times out. I didn't find the verbose logging to be super helpful, unless it makes sense to either of you? @tofumatt @sole  The only part I followed was "TRYING TO OPEN AN OLD VERSION?????"

```bash
2015-01-21 16:17:43.733 b2g-bin[4742:507] *** WARNING: Method userSpaceScaleFactor in class NSWindow is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
PermissionsTable.jsm: expandPermissions: Unknown Permission: video-capturePermissionsInstaller.jsm: 'video-capture' is not a valid Webapps permission name.PermissionsTable.jsm: expandPermissions: Unknown Permission: video-capturePermissionsInstaller.jsm: 'video-capture' is not a valid Webapps permission name.processing -dbgport command line option
EXCEPTION setting dbgport into preferences '[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIPrefBranch.setCharPref]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: chrome://prosthesis/content/dbgport.js :: <TOP_LEVEL> :: line 28"  data: no]': undefined
JavaScript error: chrome://browser/content/shell.js, line 298: this.contentBrowser is null
System JS : ERROR resource://gre/modules/ObjectWrapper.jsm:75 - Error: Expected an object as the target scope
Cannot open Settings DB. Trying to open an old version?
System JS : ERROR resource://gre/modules/IndexedDBHelper.jsm:116 - UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code.
Cannot open Settings DB. Trying to open an old version?
Cannot open Settings DB. Trying to open an old version?
Cannot open Settings DB. Trying to open an old version?
Cannot open Settings DB. Trying to open an old version?
Cannot open Settings DB. Trying to open an old version?
Cannot open Settings DB. Trying to open an old version?
Cannot open Settings DB. Trying to open an old version?
Cannot open Settings DB. Trying to open an old version?
Cannot open Settings DB. Trying to open an old version?
Cannot open Settings DB. Trying to open an old version?
Cannot open Settings DB. Trying to open an old version?
Cannot open Settings DB. Trying to open an old version?
System JS : ERROR resource://gre/modules/IndexedDBHelper.jsm:116 - UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code.
Cannot open Settings DB. Trying to open an old version?
Cannot open Settings DB. Trying to open an old version?
Error starting simulator [Error: Timed out trying to connect to the simulator in 8002]
```

**Comment by tofumatt** [comment]
First thought is maybe you need to pass it a profile or it uses whatever is the "default" (which if you've run a newer version might be causing the settings DB error)?

That said, I can try to check out your branch and see if I can get more info out of it. But the errors don't make much sense to me either :disappointed:

**Comment by sole** [comment]
Yeah you need to use the same profile that `find-simulators` finds. It might be easy to just test this using a local symlinked find-simulators and `start-simulator` passing a version (e.g. `startSimulator({ version: '1.3' }) so you don't have to bother with all the "quoting" of "the full paths" "to the profile" "and the binary"!

**Comment by brittanystoroz** [comment]
I believe my branch is using the same profile that `find-simulators` finds? Unless I'm misunderstanding. I've only adjusted the binary path, the profile path has remained the same. @sole I'm testing this exactly as you've described

**Comment by sole** [comment]
ooh maybe it's a bug! ?

@brittanystoroz you should ask ochameau or jryans in #devtools

**Comment by brittanystoroz** [comment]
Will do

**Comment by jryans** [comment]
The issue seems to be the "-start-debugger-server" option.

1.2 - 1.3 used "-dbgport" instead. 1.4 and later use "-start-debugger-server". It works locally with this change.

**Comment by brittanystoroz** [comment]
Thanks @jryans - I'll try implementing this in https://github.com/mozilla/node-firefox-start-simulator

**Comment by brittanystoroz** [comment]
So with the issue in start-simulator resolved, I can clean up my fork and PR this. Question for anyone who might know @sole @tofumatt @jryans --

In my diff right now I have a directory in the binary path hard-coded as /mac64 https://github.com/brittanystoroz/node-firefox-find-simulators/commit/5fe0694ce7c4ca4db45956a95121eb8c457b77be#diff-168726dbe96b3ce427e7fedce31bb0bcR67

Is there a chance this could be mac32 if someone is on an old machine?  Is there a way to detect 32 vs. 64 bit in node? ¯\_(ツ)_/¯

**Comment by jryans** [comment]
> In my diff right now I have a directory in the binary path hard-coded as /mac64 brittanystoroz@5fe0694#diff-168726dbe96b3ce427e7fedce31bb0bcR67
> 
> Is there a chance this could be mac32 if someone is on an old machine? Is there a way to detect 32 vs. 64 bit in node? ¯_(ツ)_/¯

You don't need to worry for Mac, but you do for Linux[1].

Looks like you can use `process.arch`[2].

[1]: https://github.com/mozilla/r2d2b2g/blob/release-7.0/addon/lib/simulator-process.js#L169
[2]: http://nodejs.org/api/process.html#process_process_arch

**Comment by tofumatt** [comment]
I think it would just be "Mac" but I mean virtually ANY Mac since forever is running 64-bit Intel. We'd be forsaking 2006-2007 Mac Minis and MacBooks, mostly. I personally am okay not supporting them until someone who actually has one submits a PR with a fix.
